# Generated by Django 6.0 on 2026-01-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_alter_aluguel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='valor_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
