# Generated by Django 6.0 on 2026-01-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_carro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('alugado', 'Alugado'), ('indisponivel', 'Indisponível')], default='disponivel', max_length=20),
        ),
    ]
