# Generated by Django 6.0 on 2026-01-05 17:29

from django.db import migrations

def criar_grupos(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    #  Grupo funcionários e clientes
    funcionarios_group, created = Group.objects.get_or_create(name='Funcionários')
    clientes_group, created = Group.objects.get_or_create(name='Clientes')

def remover_grupos(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    Group.objects.filter(name='Funcionários').delete()
    Group.objects.filter(name='Clientes').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_perfilcliente_id'),
    ]

    operations = [
        migrations.RunPython(criar_grupos, remover_grupos),
    ]
